[[Control]]
name = "control1"
input = "linear1"
id = "control1"
active = true

[[Linear]]
name = "linear1"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100
input = "custom_temp"

[[Flat]]
name = "flat1"
value = 50

[[Target]]
name = "target1"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100




[[CustomTemp]]
name = "custom_temp"
kind = "Average"
input = [
    "temp1",
    "temp2",
]





[[Temp]]
name = "temp1"
id = "temp1"

[[Temp]]
name = "temp2"
id = "temp2"